services:
  - type: web
    name: nutrigene
    env: python
    buildCommand: pip install -r backend/backend_requirements.txt
    startCommand: gunicorn --chdir backend backend_app:app
    envVars:
      - key: DATABASE_URL
        sync: false
